# Generated by Django 6.0.6 on 2026-06-12 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_truckstop_id', models.IntegerField()),
                ('truckstop_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fuel_stations',
                'unique_together': {('opis_truckstop_id', 'address')},
            },
        ),
        migrations.CreateModel(
            name='FuelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_id', models.IntegerField()),
                ('retail_price', models.DecimalField(decimal_places=3, max_digits=8)),
                ('is_current', models.BooleanField(default=True)),
                ('effective_date', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='fuel.fuelstation')),
            ],
            options={
                'db_table': 'fuel_prices',
                'indexes': [models.Index(fields=['rack_id'], name='fuel_prices_rack_id_6d4ed9_idx'), models.Index(fields=['is_current'], name='fuel_prices_is_curr_94284c_idx')],
            },
        ),
    ]
