# Generated by Django 6.0.6 on 2026-06-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuelprice',
            old_name='effective_date',
            new_name='effective_from',
        ),
        migrations.AddField(
            model_name='fuelprice',
            name='effective_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
